### PR TITLE
mark old versions of liquidsoap conflicting with camlimages >=5.0.5

### PR DESCRIPTION
**Pull request by haochenx**
This should fix revdeps failures for liquidsoaps in https://github.com/ocaml/opam-repository/pull/24924.

### CODE REVIEW

**Comment by mseri** [comment]
For future reference, it fails with
```
# OCAMLOPT -c decoder/image/camlimages_decoder.ml
# File "decoder/image/camlimages_decoder.ml", line 31, characters 12-24:
# 31 |   let img = OImages.load filename [] in
#                  ^^^^^^^^^^^^
# Error: Unbound module OImages
# Hint: Did you mean Image?
# make[2]: *** [../Makefile.rules:122: decoder/image/camlimages_decoder.cmx] Error 2
# make[2]: Leaving directory '/home/opam/.opam/4.14/.opam-switch/build/liquidsoap.2.0.7/src'
# make[1]: *** [../Makefile.rules:69: all-auto-ocaml-prog] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.14/.opam-switch/build/liquidsoap.2.0.7/src'
# make: *** [Makefile.rules:29: all-subdirs] Error 2
```

**Comment by mseri** [comment]
@haochenx thanks, can you send this pull request with the revdeps to `ocaml/opam-repository` instead? I just noticed it is on camlspotter repo

**Comment by haochenx** [comment]
> can you send this pull request with the revdeps to ocaml/opam-repository instead? I just noticed it is on camlspotter repo

As I don't have the permission to update Jun's PR, I can only either send a PR that updates the revdeps before camlimages.5.0.5 is merged (make the information chain slightly harder to follow), or a completely new PR superseding Jun's current one (which isn't a polite thing to do IMO.)

Neither is favorable so I do prefer to wait for a couple of days to see how Jun's going to respond.

**Comment by haochenx** [comment]
Or if https://github.com/ocaml/opam-repository/pull/24924 is merged in the meanwhile the concerns will be gone
